spring.application.name: notification-service
server.port: 8083
server.shutdown: graceful
spring.mvc.problemdetails.enabled: true

######## Notification Service Configuration  #########
notification.order-events-exchange: orders-exchange
notification.new-orders-queue: new-orders
notification.delivered-orders-queue: delivered-orders
notification.cancelled-orders-queue: cancelled-orders
notification.error-orders-queue: error-orders
notification.support-email: ichensoul@gmall.com

######## Actuator Configuration  #########
management.info.git.mode: full
management.endpoints.web.exposure.include: "*"
management.endpoint.health.show-details: always
management.endpoint.health.probes.enabled: true
management.metrics.tags.application: ${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.server.requests: true
management.observations.key-values.application: ${spring.application.name}
management.tracing.enabled: false
management.tracing.sampling.probability: 1.0


######## Database Configuration  #########
spring.datasource.url: jdbc:postgresql://localhost:35432/postgres
spring.datasource.username: postgres
spring.datasource.password: postgres
spring.jpa.open-in-view: false
spring.jpa.show-sql: true

######## RabbitMQ Configuration  #########
spring.rabbitmq.host: localhost
spring.rabbitmq.port: 5672
spring.rabbitmq.username: guest
spring.rabbitmq.password: guest

############# Mail Properties ###########
spring.mail.host: 127.0.0.1
spring.mail.port: 1025
spring.mail.username: PLACEHOLDER
spring.mail.password: PLACEHOLDER
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true

spring.config.import: optional:configserver:http://localhost:8888

