name: 'spring-boot-microservices-course'
services:
  product-service:
    image: chensoul/bookstore-product-service
    container_name: product-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MANAGEMENT.TRACING.ENABLED=true
      - MANAGEMENT.ZIPKIN.TRACING.ENDPOINT=http://tempo:9411/api/v2/spans
      - SPRING.DATASOURCE.URL=jdbc:postgresql://product-db:5432/postgres
      - SWAGGER.API-GATEWAY-URL=http://api-gateway:8989/product
    ports:
      - "8081:8081"
    restart: unless-stopped
    depends_on:
      product-db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    labels:
      logging: "promtail"

  order-service:
    image: chensoul/bookstore-order-service
    container_name: order-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MANAGEMENT.TRACING.ENABLED=true
      - MANAGEMENT.ZIPKIN.TRACING.ENDPOINT=http://tempo:9411/api/v2/spans
      - SPRING.DATASOURCE.URL=jdbc:postgresql://order-db:5432/postgres
      - SPRING.RABBITMQ.HOST=bookstore-rabbitmq
      - OAUTH2.SERVER-URL=http://keycloak:9191
      - SWAGGER.API-GATEWAY-URL=http://api-gateway:8989/order
      - ORDERS.CATALOG-SERVICE-URL=http://api-gateway:8989/product
    ports:
      - "8082:8082"
    restart: unless-stopped
    depends_on:
      order-db:
        condition: service_healthy
      bookstore-rabbitmq:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    labels:
      logging: "promtail"

  notification-service:
    image: chensoul/bookstore-notification-service
    container_name: notification-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MANAGEMENT.TRACING.ENABLED=true
      - MANAGEMENT.ZIPKIN.TRACING.ENDPOINT=http://tempo:9411/api/v2/spans
      - SPRING.DATASOURCE.URL=jdbc:postgresql://notification-db:5432/postgres
      - SPRING.RABBITMQ.HOST=bookstore-rabbitmq
      - SPRING.MAIL.HOST=mailhog
    ports:
      - "8083:8083"
    restart: unless-stopped
    depends_on:
      notification-db:
        condition: service_healthy
      bookstore-rabbitmq:
        condition: service_healthy
      mailhog:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 700m
    labels:
      logging: "promtail"

  user-service:
    image: chensoul/bookstore-user-service
    container_name: user-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MANAGEMENT.TRACING.ENABLED=true
      - MANAGEMENT.ZIPKIN.TRACING.ENDPOINT=http://tempo:9411/api/v2/spans
      - SPRING.DATASOURCE.URL=jdbc:postgresql://user-db:5432/postgres
      - SWAGGER.API-GATEWAY-URL=http://api-gateway:8989/user
    ports:
      - "8084:8084"
    restart: unless-stopped
    depends_on:
      product-db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    labels:
      logging: "promtail"

  config-server:
    image: chensoul/bookstore-config-server
    container_name: ft-config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8888:8888"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m

  api-gateway:
    image: chensoul/bookstore-api-gateway
    container_name: api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MANAGEMENT.TRACING.ENABLED=true
      - MANAGEMENT.ZIPKIN.TRACING.ENDPOINT=http://tempo:9411/api/v2/spans
      - CATALOG_SERVICE_URL=http://product-service:8081
      - ORDER_SERVICE_URL=http://order-service:8082
    ports:
      - "8989:8989"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m
    labels:
      logging: "promtail"

  bookstore-webapp:
    image: chensoul/bookstore-webapp
    container_name: bookstore-webapp
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MANAGEMENT.TRACING.ENABLED=true
      - MANAGEMENT.ZIPKIN.TRACING.ENDPOINT=http://tempo:9411/api/v2/spans
      - BOOKSTORE.API-GATEWAY-URL=http://api-gateway:8989
      - OAUTH2.SERVER-URL=http://keycloak:9191
    ports:
      - "8080:8080"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m
    labels:
      logging: "promtail"