spring.application.name: product-service
server.port: 8081
server.shutdown: graceful
spring.mvc.problemdetails.enabled: true

######## Actuator Configuration  #########
management.info.git.mode: full
management.endpoints.web.exposure.include: "*"
management.endpoint.health.show-details: always
management.endpoint.health.probes.enabled: true
management.metrics.tags.application: ${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.server.requests: true
management.observations.key-values.application: ${spring.application.name}
management.tracing.enabled: false
management.tracing.sampling.probability: 1.0


######## Swagger Configuration  #########
bookstore.openapi.title: Product Service API
bookstore.openapi.description: Product Service API Swagger Documentation
bookstore.openapi.versio: v1.0.0
bookstore.openapi.contact.name: chensoul
bookstore.openapi.contact.email: ichensoul@gmall.com

######## Database Configuration  #########
spring.datasource.url: jdbc:postgresql://localhost:15432/postgres
spring.datasource.username: postgres
spring.datasource.password: postgres
spring.jpa.open-in-view: false

spring.config.import: optional:configserver:http://localhost:8888

