spring.application.name: bookstore-webapp
server.port: 8080
server.shutdown: graceful
spring.mvc.problemdetails.enabled: true

######## BookStore Application Configuration  #########
bookstore.api-gateway-url: http://localhost:8989

######## Actuator Configuration  #########
management.info.git.mode: full
management.endpoints.web.exposure.include: "*"
management.endpoint.health.show-details: always
management.endpoint.health.probes.enabled: true
management.metrics.tags.application: ${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.server.requests: true
management.observations.key-values.application: ${spring.application.name}
management.tracing.enabled: false
management.tracing.sampling.probability: 1.0
management.zipkin.tracing.endpoint: http://localhost:9411/api/v2/spans

spring.config.import: optional:configserver:http://localhost:8888

######## OAuth2 Security Configuration  #########
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID:Ov23likOi21AwqpT9WUP}
            client-secret: ${GITHUB_CLIENT_SECRET:2cb389b00b067c731e073864cf3d744fb36ed92e}
            scope: read:user
            authorization-grant-type: authorization_code
            client_authentication_method: client_secret_post

spring.security.oauth2.client.registration.keycloak.client-id: bookstore-webapp
spring.security.oauth2.client.registration.keycloak.client-secret: P1sibsIrELBhmvK18BOzw1bUl96DcP2z
spring.security.oauth2.client.registration.keycloak.authorization-grant-type: authorization_code
spring.security.oauth2.client.registration.keycloak.scope: openid, profile
spring.security.oauth2.client.registration.keycloak.redirect-uri: "{baseUrl}/login/oauth2/code/bookstore-webapp"

oauth2.realm-url: http://localhost:9191/realms/bookstore
spring.security.oauth2.client.provider.keycloak.issuer-uri: ${oauth2.realm-url}
#spring.security.oauth2.client.provider.bookstore-webapp.authorization-uri: ${oauth2.realm-url}/protocol/openid-connect/auth
#spring.security.oauth2.client.provider.bookstore-webapp.token-uri: ${oauth2.realm-url}/protocol/openid-connect/token
#spring.security.oauth2.client.provider.bookstore-webapp.jwk-set-uri: ${oauth2.realm-url}/protocol/openid-connect/certs
#spring.security.oauth2.client.provider.bookstore-webapp.user-info-uri: ${oauth2.realm-url}/protocol/openid-connect/userinfo

