name: API Gateway

on:
  push:
    branches:
      - 'main'
    paths:
      - api-gateway/**
      - bookstore-webapp/**
      - user-service/**
      - product-service/**
      - order-service/**
      - notification-service/**
      - config-server/**
  pull_request:
    branches:
      - 'main'
    paths:
      - api-gateway/**
      - bookstore-webapp/**
      - user-service/**
      - product-service/**
      - order-service/**
      - notification-service/**
      - config-server/**

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Make Maven wrapper executable
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw -ntp verify

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Publish Docker Image
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          ./mvnw -pl user-service spring-boot:build-image -DskipTests
          ./mvnw -pl product-service spring-boot:build-image -DskipTests
          ./mvnw -pl order-service spring-boot:build-image -DskipTests
          ./mvnw -pl notification-service spring-boot:build-image -DskipTests
          ./mvnw -pl config-server spring-boot:build-image -DskipTests
          ./mvnw -pl api-gateway spring-boot:build-image -DskipTests
          ./mvnw -pl bookstore-webapp spring-boot:build-image -DskipTests
          echo "Pushing the image $DOCKER_IMAGE_NAME to Docker Hub..."
          docker push --all-tags $DOCKER_IMAGE_NAME
